export enum ServersActionTypes {
  FETCH_SERVERS_REQUEST = "@@servers/FETCH_SERVERS_REQUEST",
  FETCH_SERVERS_SUCCESS = "@@servers/FETCH_SERVERS_SUCCESS",
  FETCH_SERVERS_ERROR = "@@servers/FETCH_SERVERS_ERROR",
  DELETE_SERVERS = "@@servers/DELETE_SERVERS",
}
